# Server
server.port=4000

# MongoDB
spring.data.mongodb.uri=mongodb+srv://walkathon:walkathon@walkathon.xwkvogr.mongodb.net/Walkathon?appName=Walkathon

# JWT
app.jwt.secret="your-secret-key"
app.jwt.expiration=86400000

# Logging
logging.level.com.sgarden=DEBUG
spring.output.ansi.enabled=ALWAYS
